spring:
  application:
    name: "EUREKA SERVER"

server:
  port: 9004

eureka:  client:
    service-url:
      defaultZone: http://localhost:9004/eureka    register-with-eureka: false
    fetch-registry: false