eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9004/eureka}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
spring:
  h2:
    enabled:true
